# Generated by Django 5.1.5 on 2025-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit_AI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='protien',
            new_name='protein',
        ),
        migrations.RenameField(
            model_name='userhistory',
            old_name='protien',
            new_name='protein',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
