# Generated by Django 5.1.5 on 2025-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit_AI', '0004_rename_excersise_exercises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('steps_goal', models.DecimalField(decimal_places=0, default=10000, max_digits=5)),
                ('sleep_goal', models.DecimalField(decimal_places=0, default=8, max_digits=2)),
                ('calories_goal', models.DecimalField(decimal_places=0, default=2000, max_digits=5)),
                ('weight_goal', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('protein_goal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight_goal',
        ),
    ]
