# Generated by Django 5.1.5 on 2025-01-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit_AI', '0005_usergoals_remove_userprofile_weight_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sleep',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='usergoals',
            name='protein_goal',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usergoals',
            name='sleep_goal',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=2),
        ),
    ]
