# Generated by Django 5.1.5 on 2025-02-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit_AI', '0007_alter_user_sleep_alter_usergoals_sleep_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='Excersise_done',
            field=models.ManyToManyField(related_name='historyexcersise', to='Fit_AI.fooditem'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='food',
            field=models.ManyToManyField(related_name='historydiets', to='Fit_AI.fooditem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sleep',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usergoals',
            name='sleep_goal',
            field=models.DecimalField(decimal_places=3, default=8.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='sleep',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
